spring:
  application:
    name: nacos-mcp-server
  main:
    banner-mode: off
  ai:
    mcp:
      server:
        name: nacos-mcp-server
        version: v2.4.3
        sse-endpoint: /sse
        instructions: "Nacos MCP AI Tools - 提供Nacos集群管理的AI工具"

nacos:
  server: ${NACOS_SERVER:http://192.168.1.242:8848}
  username: ${NACOS_USERNAME:nacos}
  password: ${NACOS_PASSWORD:nacos}

logging:
  level:
    com.bubua12.mcp.nacos: ${APP_LOG_LEVEL:INFO}
    org.springframework.web.reactive.function.client: ${HTTP_LOG_LEVEL:INFO}
